<?php

namespace Database\Seeders;

use App\Models\CertificationModule;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CertificationModuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rows = [
            [
                'code' => 'CM001',
                'module_title' => 'Foundation Safety',
                'level' => 'Basic',
                'competency' => 'Safety',
                'group_certification' => 'PPT AND PPM',
                'points_per_module' => 5,
                'new_gex' => 0.50,
                'duration' => 60,
                'major_component' => 'ALL INNER & OUTER PARTS',
                'mach_model' => 'ALL UNIT MODEL',
                'theory_passing_score' => 70.0,
                'practical_passing_score' => 75.0,
                'is_active' => true,
            ],
            [
                'code' => 'CM002',
                'module_title' => 'Quality Essentials',
                'level' => 'Basic',
                'competency' => 'Quality',
                'group_certification' => 'PPT AND PPM',
                'points_per_module' => 6,
                'new_gex' => 0.55,
                'duration' => 75,
                'major_component' => 'ALL INNER & OUTER PARTS',
                'mach_model' => 'ALL UNIT MODEL',
                'theory_passing_score' => 70.0,
                'practical_passing_score' => 75.0,
                'is_active' => true,
            ],
            [
                'code' => 'CM003',
                'module_title' => 'Tools Handling',
                'level' => 'Basic',
                'competency' => 'Operations',
                'group_certification' => 'PPT AND PPM',
                'points_per_module' => 6,
                'new_gex' => 0.60,
                'duration' => 90,
                'major_component' => 'ALL INNER & OUTER PARTS',
                'mach_model' => 'ALL UNIT MODEL',
                'theory_passing_score' => 70.0,
                'practical_passing_score' => 75.0,
                'is_active' => true,
            ],
            [
                'code' => 'CM004',
                'module_title' => 'Maintenance 101',
                'level' => 'Basic',
                'competency' => 'Maintenance',
                'group_certification' => 'PPT AND PPM',
                'points_per_module' => 7,
                'new_gex' => 0.65,
                'duration' => 90,
                'major_component' => 'ALL INNER & OUTER PARTS',
                'mach_model' => 'ALL UNIT MODEL',
                'theory_passing_score' => 70.0,
                'practical_passing_score' => 75.0,
                'is_active' => true,
            ],
            [
                'code' => 'CM005',
                'module_title' => 'Operational Basics',
                'level' => 'Basic',
                'competency' => 'Operations',
                'group_certification' => 'PPT AND PPM',
                'points_per_module' => 7,
                'new_gex' => 0.70,
                'duration' => 60,
                'major_component' => 'ALL INNER & OUTER PARTS',
                'mach_model' => 'ALL UNIT MODEL',
                'theory_passing_score' => 72.0,
                'practical_passing_score' => 76.0,
                'is_active' => true,
            ],
            [
                'code' => 'CM006',
                'module_title' => 'Advanced Safety',
                'level' => 'Intermediate',
                'competency' => 'Safety',
                'group_certification' => 'PPT AND PPM',
                'points_per_module' => 8,
                'new_gex' => 0.80,
                'duration' => 120,
                'major_component' => 'ALL INNER & OUTER PARTS',
                'mach_model' => 'ALL UNIT MODEL',
                'theory_passing_score' => 75.0,
                'practical_passing_score' => 78.0,
                'is_active' => true,
            ],
            [
                'code' => 'CM007',
                'module_title' => 'Quality Control',
                'level' => 'Intermediate',
                'competency' => 'Quality',
                'group_certification' => 'PPT AND PPM',
                'points_per_module' => 8,
                'new_gex' => 0.85,
                'duration' => 120,
                'major_component' => 'ALL INNER & OUTER PARTS',
                'mach_model' => 'ALL UNIT MODEL',
                'theory_passing_score' => 75.0,
                'practical_passing_score' => 78.0,
                'is_active' => true,
            ],
            [
                'code' => 'CM008',
                'module_title' => 'Diagnostics',
                'level' => 'Intermediate',
                'competency' => 'Maintenance',
                'group_certification' => 'PPT AND PPM',
                'points_per_module' => 9,
                'new_gex' => 0.90,
                'duration' => 150,
                'major_component' => 'ALL INNER & OUTER PARTS',
                'mach_model' => 'ALL UNIT MODEL',
                'theory_passing_score' => 75.0,
                'practical_passing_score' => 80.0,
                'is_active' => true,
            ],
            [
                'code' => 'CM009',
                'module_title' => 'Process Optimization',
                'level' => 'Intermediate',
                'competency' => 'Operations',
                'group_certification' => 'PPT AND PPM',
                'points_per_module' => 9,
                'new_gex' => 0.95,
                'duration' => 150,
                'major_component' => 'ALL INNER & OUTER PARTS',
                'mach_model' => 'ALL UNIT MODEL',
                'theory_passing_score' => 76.0,
                'practical_passing_score' => 80.0,
                'is_active' => true,
            ],
            [
                'code' => 'CM010',
                'module_title' => 'Advanced Tools',
                'level' => 'Intermediate',
                'competency' => 'Operations',
                'group_certification' => 'PPT AND PPM',
                'points_per_module' => 10,
                'new_gex' => 1.00,
                'duration' => 120,
                'major_component' => 'ALL INNER & OUTER PARTS',
                'mach_model' => 'ALL UNIT MODEL',
                'theory_passing_score' => 76.0,
                'practical_passing_score' => 80.0,
                'is_active' => true,
            ],
            [
                'code' => 'CM011',
                'module_title' => 'Safety Leadership',
                'level' => 'Advanced',
                'competency' => 'Safety',
                'group_certification' => 'PPT AND PPM',
                'points_per_module' => 10,
                'new_gex' => 1.10,
                'duration' => 180,
                'major_component' => 'ALL INNER & OUTER PARTS',
                'mach_model' => 'ALL UNIT MODEL',
                'theory_passing_score' => 80.0,
                'practical_passing_score' => 82.0,
                'is_active' => true,
            ],
            [
                'code' => 'CM012',
                'module_title' => 'Quality Assurance',
                'level' => 'Advanced',
                'competency' => 'Quality',
                'group_certification' => 'PPT AND PPM',
                'points_per_module' => 11,
                'new_gex' => 1.15,
                'duration' => 180,
                'major_component' => 'ALL INNER & OUTER PARTS',
                'mach_model' => 'ALL UNIT MODEL',
                'theory_passing_score' => 80.0,
                'practical_passing_score' => 82.0,
                'is_active' => true,
            ],
            [
                'code' => 'CM013',
                'module_title' => 'Predictive Maintenance',
                'level' => 'Advanced',
                'competency' => 'Maintenance',
                'group_certification' => 'PPT AND PPM',
                'points_per_module' => 12,
                'new_gex' => 1.20,
                'duration' => 210,
                'major_component' => 'ALL INNER & OUTER PARTS',
                'mach_model' => 'ALL UNIT MODEL',
                'theory_passing_score' => 80.0,
                'practical_passing_score' => 84.0,
                'is_active' => true,
            ],
            [
                'code' => 'CM014',
                'module_title' => 'Lean Operations',
                'level' => 'Advanced',
                'competency' => 'Operations',
                'group_certification' => 'PPT AND PPM',
                'points_per_module' => 12,
                'new_gex' => 1.25,
                'duration' => 210,
                'major_component' => 'ALL INNER & OUTER PARTS',
                'mach_model' => 'ALL UNIT MODEL',
                'theory_passing_score' => 80.0,
                'practical_passing_score' => 84.0,
                'is_active' => true,
            ],
            [
                'code' => 'CM015',
                'module_title' => 'Expert Review',
                'level' => 'Advanced',
                'competency' => 'Quality',
                'group_certification' => 'PPT AND PPM',
                'points_per_module' => 13,
                'new_gex' => 1.30,
                'duration' => 240,
                'major_component' => 'ALL INNER & OUTER PARTS',
                'mach_model' => 'ALL UNIT MODEL',
                'theory_passing_score' => 82.0,
                'practical_passing_score' => 85.0,
                'is_active' => true,
            ],
        ];

        foreach ($rows as $row) {
            CertificationModule::updateOrCreate(
                ['code' => $row['code']],
                $row
            );
        }
    }
}
