<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Course;
use App\Models\LearningModule;
use Illuminate\Support\Str;

class LearningModuleSeeder extends Seeder
{
    /**
     * Seed simple learning modules for each course.
     */
    public function run(): void
    {
        $courses = Course::all();
        if ($courses->isEmpty()) {
            $this->command?->warn('No courses found. Skipping LearningModuleSeeder.');
            return;
        }

        // Configurable bounds
        $MIN_PER_COURSE = 3; // adjust as needed
        $MAX_PER_COURSE = 6; // adjust as needed
        if ($MIN_PER_COURSE > $MAX_PER_COURSE) {
            [$MIN_PER_COURSE, $MAX_PER_COURSE] = [$MAX_PER_COURSE, $MIN_PER_COURSE];
        }

        $total = 0;
        foreach ($courses as $course) {
            $existing = LearningModule::where('course_id', $course->id)->count();
            if ($existing > 0) {
                $this->command?->line("Course {$course->id} already has {$existing} modules. Skipping.");
                continue;
            }

            $count = random_int($MIN_PER_COURSE, $MAX_PER_COURSE);
            $rows = [];
            for ($i = 1; $i <= $count; $i++) {
                $title = "Module $i: " . Str::title(Str::replace('-', ' ', Str::slug($course->title)));
                $rows[] = [
                    'course_id'     => $course->id,
                    'title'         => $title,
                    'description'   => 'Autogenerated module for course ' . $course->title,
                    'content_type'  => random_int(0, 1) ? 'video' : 'pdf',
                    'url'           => 'https://example.com/content/' . Str::uuid(),
                    'is_completed'  => false,
                    'created_at'    => now(),
                    'updated_at'    => now(),
                ];
            }

            LearningModule::insert($rows);
            $total += count($rows);
            $this->command?->info('Created ' . count($rows) . " modules for course ID {$course->id}");
        }

        if ($total === 0) {
            $this->command?->line('No new modules inserted.');
        } else {
            $this->command?->info("Total learning modules inserted: {$total}");
        }
    }
}
